### ISSUE TITLE
List rendering issue.

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/fable#7]
The following

```toml
[[pages]]
template = "Basic"
title = "Outline"
text = """
- Context
    - What is a rack scale computer?
    - Why is network programmability important?
"""
```

Renders like this

<img width="729" alt="image" src="https://github.com/oxidecomputer/fable/assets/1010256/83f3e546-7719-4d59-9a8a-9518e0f49a44">

But what i would expect is this

<img width="767" alt="image" src="https://github.com/oxidecomputer/fable/assets/1010256/5a0e463b-591e-46fd-9125-68c02bad5eac">

A workaround is this

```toml
[[pages]]
template = "Basic"
title = "Outline"
text = """
- &nbsp;
    - Context
        - What is a rack scale computer?
        - Why is network programmability important?
"""
```
